version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: util/readthedocs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: doc/source/conf.py
