/* Copyright (c) 2006-2012 Filip Wasilewski <http://en.ig.ma/>
 * Copyright (c) 2012-2016 The PyWavelets Developers
 *                         <https://github.com/PyWavelets/pywt>
 * See COPYING for license details.
 */

/* Common constants, typedefs and functions */

#pragma once

/* ##### Typedefs ##### */

#ifdef PY_EXTENSION
    /* another declaration is in .c file generated by Pyrex */
    #ifndef PY_SSIZE_T_CLEAN
        #define PY_SSIZE_T_CLEAN
        #include "Python.h"
        #include "structmember.h"
        #ifndef PY_LONG_LONG
            #define PY_LONG_LONG LONG_LONG
        #endif
    #else
        #include "Python.h"
    #endif

    /* on Solaris/SmartOS system, index_t is used in sys/types.h, so use pytw_index_t */
    typedef Py_ssize_t pywt_index_t;

#else
    typedef int pywt_index_t;
#endif

#include <stdlib.h>
#include <memory.h>

/* ##### Complex types #####
 *
 * Portable complex types and accessors, following NumPy's approach (see
 * numpy/_core/include/numpy/npy_common.h and npy_math.h): MSVC has no C99
 * `_Complex` and provides the struct-based `_Fcomplex`/`_Dcomplex` instead,
 * with no arithmetic operators.  All complex arithmetic in the C sources
 * therefore goes through the inline helpers below, which only rely on the
 * layout (two consecutive reals) that all representations share.
 *
 * For templating, the typedef names must not contain spaces.
 *
 * PYWT_TEST_STRUCT_COMPLEX is a testing hook: it swaps in plain structs with
 * the same layout and no operators, so that MSVC-like semantics can be
 * compiled and tested with any compiler (used by the struct-complex CI job).
 * The structs match the ones NumPy's headers use when compiled as C++, where
 * C99 `_Complex` is also unavailable.
 */

#ifdef PYWT_TEST_STRUCT_COMPLEX

typedef struct
{
    float _Val[2];
} float_complex;

typedef struct
{
    double _Val[2];
} double_complex;

#else

#include <complex.h>

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER) && !defined(__INTEL_LLVM_COMPILER)
typedef _Fcomplex float_complex;
typedef _Dcomplex double_complex;
#else
typedef float _Complex float_complex;
typedef double _Complex double_complex;
#endif

#endif

static inline float pywt_crealf(const float_complex z)
{
#ifdef PYWT_TEST_STRUCT_COMPLEX
    return z._Val[0];
#else
    return crealf(z);
#endif
}

static inline float pywt_cimagf(const float_complex z)
{
#ifdef PYWT_TEST_STRUCT_COMPLEX
    return z._Val[1];
#else
    return cimagf(z);
#endif
}

static inline void pywt_csetrealf(float_complex *z, const float r)
{
    ((float *) z)[0] = r;
}

static inline void pywt_csetimagf(float_complex *z, const float i)
{
    ((float *) z)[1] = i;
}

static inline double pywt_creal(const double_complex z)
{
#ifdef PYWT_TEST_STRUCT_COMPLEX
    return z._Val[0];
#else
    return creal(z);
#endif
}

static inline double pywt_cimag(const double_complex z)
{
#ifdef PYWT_TEST_STRUCT_COMPLEX
    return z._Val[1];
#else
    return cimag(z);
#endif
}

static inline void pywt_csetreal(double_complex *z, const double r)
{
    ((double *) z)[0] = r;
}

static inline void pywt_csetimag(double_complex *z, const double i)
{
    ((double *) z)[1] = i;
}

/* Arithmetic helpers used by the type-templated convolution kernels; the
 * CAT(TYPE, _op) spellings must exist for every TYPE the templates are
 * instantiated with.  The complex variants only need a real second factor in
 * _mul because the wavelet filters are always real. */

static inline float float_zero(void) { return 0.0f; }
static inline float float_add(const float a, const float b) { return a + b; }
static inline float float_sub(const float a, const float b) { return a - b; }
static inline float float_mul(const float a, const float b) { return a * b; }

static inline double double_zero(void) { return 0.0; }
static inline double double_add(const double a, const double b) { return a + b; }
static inline double double_sub(const double a, const double b) { return a - b; }
static inline double double_mul(const double a, const double b) { return a * b; }

static inline float_complex float_complex_zero(void)
{
    float_complex z;
    pywt_csetrealf(&z, 0.0f);
    pywt_csetimagf(&z, 0.0f);
    return z;
}

static inline float_complex float_complex_add(const float_complex a,
                                              const float_complex b)
{
    float_complex z;
    pywt_csetrealf(&z, pywt_crealf(a) + pywt_crealf(b));
    pywt_csetimagf(&z, pywt_cimagf(a) + pywt_cimagf(b));
    return z;
}

static inline float_complex float_complex_sub(const float_complex a,
                                              const float_complex b)
{
    float_complex z;
    pywt_csetrealf(&z, pywt_crealf(a) - pywt_crealf(b));
    pywt_csetimagf(&z, pywt_cimagf(a) - pywt_cimagf(b));
    return z;
}

static inline float_complex float_complex_mul(const float a,
                                              const float_complex b)
{
    float_complex z;
    pywt_csetrealf(&z, a * pywt_crealf(b));
    pywt_csetimagf(&z, a * pywt_cimagf(b));
    return z;
}

static inline double_complex double_complex_zero(void)
{
    double_complex z;
    pywt_csetreal(&z, 0.0);
    pywt_csetimag(&z, 0.0);
    return z;
}

static inline double_complex double_complex_add(const double_complex a,
                                                const double_complex b)
{
    double_complex z;
    pywt_csetreal(&z, pywt_creal(a) + pywt_creal(b));
    pywt_csetimag(&z, pywt_cimag(a) + pywt_cimag(b));
    return z;
}

static inline double_complex double_complex_sub(const double_complex a,
                                                const double_complex b)
{
    double_complex z;
    pywt_csetreal(&z, pywt_creal(a) - pywt_creal(b));
    pywt_csetimag(&z, pywt_cimag(a) - pywt_cimag(b));
    return z;
}

static inline double_complex double_complex_mul(const double a,
                                                const double_complex b)
{
    double_complex z;
    pywt_csetreal(&z, a * pywt_creal(b));
    pywt_csetimag(&z, a * pywt_cimag(b));
    return z;
}

/* standard c memory management */
#define wtmalloc(size)      malloc(size)
#define wtfree(ptr)         free(ptr)
#define wtcalloc(len, size) calloc(len, size)

#ifdef _MSC_VER
    #include <intrin.h>
#endif

typedef struct {
    size_t * shape;
    pywt_index_t * strides;
    size_t ndim;
} ArrayInfo;

typedef enum {
    COEF_APPROX = 0,
    COEF_DETAIL = 1,
} Coefficient;

typedef enum {
    DWT_TRANSFORM = 0,
    SWT_TRANSFORM = 1,
} DiscreteTransformType;

/* Signal extension modes */
typedef enum {
       MODE_INVALID = -1,
       MODE_ZEROPAD = 0,   /* default, signal extended with zeros */
       MODE_SYMMETRIC,     /* signal extended symmetrically (mirror)
                            * also known as half-sample symmetric
                            * For extensions greater than signal length,
                            * mirror back and forth:
                            * 2 3 3 2 1 | 1 2 3 | 3 2 1 1 2
                            */
       MODE_CONSTANT_EDGE, /* signal extended with the border value */
       MODE_SMOOTH,        /* linear extrapolation (first derivative) */
       MODE_PERIODIC,      /* signal is treated as being periodic */
       MODE_PERIODIZATION, /* signal is treated as being periodic, minimal output length */
       MODE_REFLECT,       /* signal extended symmetrically (reflect)
                            * also known as whole-sample symmetric
                            * For extensions greater than signal length,
                            * reflect back and forth without repeating edge values:
                            * 1 2 3 2 | 1 2 3 | 2 1 2 3
                            */
       MODE_ANTISYMMETRIC,  /* antisymmetric version of "MODE_SYMMETRIC"
                             * also known as half-sample antisymmetric
                             * 2 3 -3 -2 -1 | 1 2 3 | -3 -2 -1 1 2
                             */
       MODE_ANTIREFLECT,    /* antisymmetric version of "MODE_REFLECT"
                             * also known as whole-sample antisymmetric
                             * 0 -1 -2 -1 0 | 1 2 3 | 4 5 6 5 4
                             */
       MODE_MAX,
} MODE;


/* ##### Calculating buffer lengths for various operations ##### */

/*
 * Length of DWT coeffs for specified input data length, filter length and
 * signal extension mode.
 */
size_t dwt_buffer_length(size_t input_len, size_t filter_len, MODE mode);

/*
 * Length of reconstructed signal for specified input coeffs length and filter
 * length. It is used for direct reconstruction from coefficients (normal
 * convolution of upsampled coeffs with filter).
 */
size_t reconstruction_buffer_length(size_t coeffs_len, size_t filter_len);

/*
 * Length of IDWT reconstructed signal for specified input coeffs length, filter
 * length and extension mode.
 */
size_t idwt_buffer_length(size_t coeffs_len, size_t filter_len, MODE mode);

/* Length of SWT coefficients for specified input signal length (== input_len) */
size_t swt_buffer_length(size_t input_len);

/* Maximum useful level of DWT decomposition. */
unsigned char dwt_max_level(size_t input_len, size_t filter_len);

/* Maximum useful level of SWT decomposition. */
unsigned char swt_max_level(size_t input_len);
