from typing import TypeVar

import numpy as np
from numpy.typing import NDArray

from ._pywt import ModeInt, Wavelet

_CDataT = TypeVar(
    "_CDataT", bound=np.float32 | np.float64 | np.complex64 | np.complex128
)


def dwt_max_level(data_len: int, filter_len: int) -> int: ...
def dwt_coeff_len(size_t: int, filter_len: int, mode: ModeInt) -> int: ...
def dwt_single(data: NDArray[_CDataT], wavelet: Wavelet, mode: ModeInt) -> tuple[NDArray[_CDataT], NDArray[_CDataT]]: ...
def dwt_axis(data: NDArray[_CDataT], wavelet: Wavelet, mode: ModeInt, axis: int = 0) -> tuple[NDArray[_CDataT], NDArray[_CDataT]]: ...
def idwt_single(cA: NDArray[_CDataT], cD: NDArray[_CDataT], wavelet: Wavelet, mode: ModeInt) -> NDArray[_CDataT]: ...
def idwt_axis(coefs_a: NDArray[_CDataT], coefs_d: NDArray[_CDataT], wavelet: Wavelet, mode: ModeInt, axis: int = 0) -> NDArray[_CDataT]: ...
def upcoef(do_rec_a: bool, coeffs: NDArray[_CDataT], wavelet: Wavelet, level: int, take: int) -> NDArray[_CDataT]: ...
def downcoef(do_dec_a: bool, data: NDArray[_CDataT], wavelet: Wavelet, mode: ModeInt, level: int) -> NDArray[_CDataT]: ...
