from numpy.typing import NDArray

from ._pywt import CDataT, ModeInt, Wavelet

def dwt_max_level(data_len: int, filter_len: int) -> int: ...
def dwt_coeff_len(size_t: int, filter_len: int, mode: ModeInt) -> int: ...
def dwt_single(data: NDArray[CDataT], wavelet: Wavelet, mode: ModeInt) -> tuple[NDArray[CDataT], NDArray[CDataT]]: ...
def dwt_axis(data: NDArray[CDataT], wavelet: Wavelet, mode: ModeInt, axis: int = 0) -> tuple[NDArray[CDataT], NDArray[CDataT]]: ...
def idwt_single(cA: NDArray[CDataT], cD: NDArray[CDataT], wavelet: Wavelet, mode: ModeInt) -> NDArray[CDataT]: ...
def idwt_axis(coefs_a: NDArray[CDataT], coefs_d: NDArray[CDataT], wavelet: Wavelet, mode: ModeInt, axis: int = 0) -> NDArray[CDataT]: ...
def upcoef(do_rec_a: bool, coeffs: NDArray[CDataT], wavelet: Wavelet, level: int, take: int) -> NDArray[CDataT]: ...
def downcoef(do_dec_a: bool, data: NDArray[CDataT], wavelet: Wavelet, mode: ModeInt, level: int) -> NDArray[CDataT]: ...
