from numpy.typing import NDArray

from ._pywt import CDataT, Wavelet

def swt_max_level(input_len: int) -> int: ...
def swt(data: NDArray[CDataT], wavelet: Wavelet, level: int, start_level: int, trim_approx: bool = False) -> NDArray[CDataT]: ...
def swt_axis(data: NDArray[CDataT], wavelet: Wavelet, level: int, start_level: int, axis: int = 0, trim_approx: bool = False) -> NDArray[CDataT]: ...
